name: Sync To Gitee and VPS

on: # 触发条件
  push:
    branches:
      - main

  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. 检出仓库 # Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: 2. 推送到服务器私有仓库
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }} # 服务器生成的私钥，例如 -----BEGIN RSA PRIVATE KEY-----xxxx-----END RSA PRIVATE KEY-----
          ARGS: "-avz --delete" # rsync参数
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }} # 服务器ip地址，例如 1.2.3.4
          REMOTE_USER: ${{ secrets.SERVER_USER }} # 登录用户，例如 ubuntu 注意应拥有该文件夹的权限，可以在root下为用户赋权 chown -R ubuntu:755 /www/wwwroot/hexo
          TARGET: ${{ secrets.SERVER_PATH }}    # 服务器目录，例如 /www/wwwroot/hexo
          EXCLUDE: ".git/,.github/,.user.ini"            # 排除源路径中.git/ 目标路径中.user.ini 这俩不做同步操作

      - name: 3. 刷新CDN
        env:
            SECRETID: ${{ secrets.secretId }}
            SECRETKEY: ${{ secrets.secretKey }}
        run: |
          pip install --upgrade pip
          pip install tencentcloud-sdk-python
          pip install tencentcloud-sdk-python-cdn
          python3 cdn.py

      - name: 4. 备份Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:GC-ZF/Typora-Img.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:gc-zhang/Typora-Img.git
